### ISSUE TITLE
Test Build

### ISSUE THREAD

**Issue by Norskan** [DaGrisa/AphroCite#14]
Build and execute test via CMake on windows and mac. 

@DaGrisa  which compiler are you using? because then i switch to that since i dont think that you get the microsoft cl compiler to run an your mac thingy ;)

**Comment by DaGrisa** [comment]
clang LLVM compiler ... but why changing the compiler? this library should be as compiler-independent as possible

**Comment by Norskan** [comment]
yes thats true but, i want to get away from cl anyway because i can't force it to compile only for ansi c. it is a pure c++ compiler therfore i want to switch. For now i compile with gcc which seams fine for.

**Comment by Norskan** [comment]
so i can run cmake now without a problem
